# Generated by GraphQLGen
#
# Generated at: 2022-11-24T18:51:00.786
module example

abstract type MySypexGeo end

include("graphqlgen_types.jl")
include("graphqlgen_functions.jl")
end # module example
